version: '3'

services:
  api:
    container_name: asciilograph-api
    build: ./asciilograph-api
    volumes:
      - ./asciilograph-api/app:/usr/src/app
    environment:
      # should show a warning if an env variable isn't set in the shell environment
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_IMAGE_PROCESSING_QUEUE=${RABBITMQ_IMAGE_PROCESSING_QUEUE}
      - FILESERVER_ADDRESS=${FILESERVER_ADDRESS}
      - FILESERVER_USER=${FILESERVER_USER}
      - FILESERVER_PASSWORD=${FILESERVER_PASSWORD}
      - PYTHONUNBUFFERED=1
    ports:
      - 8000:8000
    depends_on:
      - rabbitmq
      - worker
      - fileserver
  worker:
    container_name: asciilograph-worker
    build: ./asciilograph-worker
    volumes:
      - ./asciilograph-worker/app:/usr/src/app
    environment:
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_IMAGE_PROCESSING_QUEUE=${RABBITMQ_IMAGE_PROCESSING_QUEUE}
      - FILESERVER_ADDRESS=${FILESERVER_ADDRESS}
      - FILESERVER_USER=${FILESERVER_USER}
      - FILESERVER_PASSWORD=${FILESERVER_PASSWORD}
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
      - fileserver
  fileserver:
    image: delfer/alpine-ftp-server
    container_name: asciilograph-fileserver
    hostname: ${FILESERVER_ADDRESS}
    environment:
      - USERS=${FILESERVER_USER}|${FILESERVER_PASSWORD}
      - ADDRESS=${FILESERVER_ADDRESS}
  rabbitmq:
    image: rabbitmq:3-management
    container_name: asciilograph-rabbit
    hostname: ${RABBITMQ_HOST}
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - 15672:15672
